### ISSUE TITLE
Crash on prepare_nfs_guest_settings.rb

### ISSUE THREAD

**Issue by Ape** [Learnosity/vagrant-nfs_guest#14]
I'm trying to use nfs_guest on Arch Linux host and Ubuntu 12.04 guest. Running  ```vagrant up``` crashes with the following message:

```
% vagrant up     
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Resuming suspended VM...
==> default: Booting VM...
/home/ape/.vagrant.d/gems/gems/vagrant-nfs_guest-0.1.4/lib/vagrant-nfs_guest/action/prepare_nfs_guest_settings.rb:98:in `read_dynamic_machine_ip': undefined method `-' for nil:NilClass (NoMethodError)
	from /home/ape/.vagrant.d/gems/gems/vagrant-nfs_guest-0.1.4/lib/vagrant-nfs_guest/action/prepare_nfs_guest_settings.rb:42:in `add_ips_to_env!'
	from /home/ape/.vagrant.d/gems/gems/vagrant-nfs_guest-0.1.4/lib/vagrant-nfs_guest/action/prepare_nfs_guest_settings.rb:21:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	...
```

**Comment by alangarf** [comment]
Sorry Arch Linux hasn't been tested. It's likely a trivial change to fix, but I've also written an alternative to the current system that will be more compatible but it replaces the base NFS plugin. This is due to the fact that Vagrant doesn't allow you to hook into the PrepareNFSSettings event unless the share is `:nfs` and `:nfs` only.

Have a look at: https://github.com/Learnosity/vagrant-nfs_guest/tree/nfs_alternate

**Comment by sivakommuri** [comment]
I am seeing this issue with "ubuntu/trusty64" as well.

**Comment by neowulf33** [comment]
I am seeing this issue with "ubuntu/trusty64" as well.

**Comment by alangarf** [comment]
@neowulf33 are you seeing the exact same error? We use ubuntu/trusty64 on about 40 development machines daily without issue. Please give me more details on what you are seeing.

**Comment by sivakommuri** [comment]
My bad - I wanted to mount the guest folder on the host machine which when trying that out - I ran into the same symptom. So, not an issue. Thanks.

**Comment by neowulf33** [comment]
My bad - I wanted to mount the guest folder on the host machine which when trying that out - I ran into the same symptom. So, not an issue. Thanks.
