### ISSUE TITLE
The capability 'nfs_unmount'

### ISSUE THREAD

**Issue by numediaweb** [Learnosity/vagrant-nfs_guest#18]
After installing the plugin on Windows 10, I get this error
```
The capability 'nfs_unmount' could not be found. This is an internal error
that users should never see. Please report a bug.
```

**Comment by alangarf** [comment]
@numediaweb Sorry Windows isn't a supported platform, I'm unsure how NFS is supported with Windows 10 and what the required commands would be to implement the required NFS functions.

Happy to receive a pull request implementing this, but I have no way of developing this myself.

Thanks.
