### ISSUE TITLE
vagrant parallels provider fails to bring up new machine

### ISSUE THREAD

**Issue by stevs986** [Learnosity/vagrant-nfs_guest#22]
OS X Version: El Capitan 10.11.2
Vagrant version: 1.7.4
Vagrant parallels plugin version: vagrant-parallels (1.5.1)

Vagrant file is really simple:
```
Vagrant.configure(2) do |config|
  config.vm.box = "parallels/ubuntu-14.04"
end
```

I got this error:
`/Users/[]/.vagrant.d/gems/gems/vagrant-nfs_guest-0.1.7/lib/vagrant-nfs_guest/providers/parallels/cap/nfs_settings.rb:7:in `nfs_settings': undefined method `provider' for nil:NilClass (NoMethodError)`

Check legal90's comment on this url: https://github.com/Parallels/vagrant-parallels/issues/238

**Comment by alangarf** [comment]
Thanks for testing the untested NEW feature! :+1:

Yup total typo in there, I've bump the patch version to v0.1.8 and that should hopefully fix it. Please let me know if it does work fine.

Thanks!

**Comment by stevs986** [comment]
@alangarf Thanks, it works like a charm!
