### ISSUE TITLE
The capability 'nfs_mount' could not be found. #84

### ISSUE THREAD

**Issue by jamiehutber** [Learnosity/vagrant-nfs_guest#27]
The capability 'nfs_mount' could not be found. This is an internal error
that users should never see. Please report a bug.

```Cmd

C:\var\www\cc-dev-env>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.3.36
    default: VirtualBox Version: 5.0
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater]   found entry for: 192.168.100.100 cc.dev
==> default: Mounting NFS shared folders from guest...
The capability 'nfs_mount' could not be found. This is an internal error
that users should never see. Please report a bug.
```

I am using 
Windows 10 64-bit
Vagrant 1.8.1
vagrant-hostsupdater (1.0.2)
vagrant-nfs_guest (0.1.8)
vagrant-share (1.1.5, system)
vagrant-winnfsd (1.1.0)

I saw a patch was added for ubuntu, I wonder if its that easy for a windows machine :)

**Comment by argh128** [comment]
Ubuntu has support for NFS... (as does MacOSX)

You might have more luck using Cygwin... but some modifications to the plugin are probably still required.

**Comment by alangarf** [comment]
Gosh I'm not sure how to configure a Windows machine programmatically to mount an NFS share. If you can figure it out and submit a PR I'm more than happy to merge. But I don't have the ability nor the time to attempt this myself.

Thanks for reporting.

**Comment by jamiehutber** [comment]
Ye, I realise now its a much bigger issue and not such a simple case of adding code on our side :)

I believe that Windows Enterprise Pro or Ultimate has NFS support. However I didn't have time for work to approve that. I am not on Ubuntu and I had this up and running in a few hours (with local environment as well).

If I work it out ever I'll post my info here.

**Comment by budhrg** [comment]
@jamiehutber You might be interested in another approach of mounting files from guest to host https://github.com/dustymabe/vagrant-sshfs
