### ISSUE TITLE
"NFS requires a host-only network to be created" when the plugin is not used

### ISSUE THREAD

**Issue by mzruya** [Learnosity/vagrant-nfs_guest#28]
Hey,
I've applied this plugin to one of my Vagrant boxes where it explicitly uses an `nfs_guest` synched folder and it works great.

The problem is in a different box that doesn't use private networking, I can't start it anymore, with the following message:
```
NFS requires a host-only network to be created.
Please add a host-only network to the machine (with either DHCP or a
static IP) for NFS to work.
```

Repro steps:
```bash
vagrant plugin install vagrant-nfs_guest
vagrant init hashicorp/precise64
vagrant up
```

removing the `vagrant-nfs_guest` plugin solves it.

It seems that `Action::MountNFS` is called regardless of if the `Vagrantfile` lists any usage of `nfs_guest` synched folders or not, is this intentional? 

I don't have much familiarity with the Vagrant plugin API, any advice on how to fix it?

Thanks!

**Comment by alangarf** [comment]
Ahh yeah I've seen that too. I'll look at a fix shortly. Thanks for reporting!

:+1:

**Comment by IvanChepurnyi** [comment]
Having the same issue, does not let me use test kitchen unless I disable vagrant-nfs_guest.

**Comment by alangarf** [comment]
Fixed with https://github.com/Learnosity/vagrant-nfs_guest/commit/e9934ccd4f1ad790bd3563a5e3d752674c947a7c

Pushing new release out. Thanks for your patience.
