### ISSUE TITLE
Are there any options?

### ISSUE THREAD

**Issue by hkirsman** [Learnosity/vagrant-nfs_guest#30]
Like there are for the "native" vagrant nsf: nfs_version, nfs_udp.
:linux__nfs_options => ['rw','no_subtree_check','all_squash','async']

**Comment by alangarf** [comment]
Yes, it works just the same as nfs_options: https://github.com/Learnosity/vagrant-nfs_guest/blob/master/lib/vagrant-nfs_guest/guests/linux/cap/nfs_server.rb#L120
