### ISSUE TITLE
`vagrant halt --force` blocks if `umount` fails

### ISSUE THREAD

**Issue by witrin** [Learnosity/vagrant-nfs_guest#34]
Somehow the nfs share was lost, so I just want to shutdown with `vagrant halt` which response with:

```
==> default: Unmounting NFS shared folders from guest...
    default: /var/www => ./www
==> default: umount: ./www: not mounted
==> default: Maybe NFS mounts still in use!
```

So I force the shutdown with `vagrant halt --force`:

```
==> default: Unmounting NFS shared folders from guest...
    default: /var/www => ./www
==> default: umount: ./www: not mounted
==> default: Maybe NFS mounts still in use!
```

I would say `--force` must not be blocked in any case regarding the docs:

>  [...] if the --force flag is specified, Vagrant will effectively just shut off power to the machine.

**Comment by alangarf** [comment]
The issue you are seeing is that your `umount` is returning `not mounted`, the plugin is expecting `not currently mounted`. This is a small issue and will be fixed and pushed out shortly. Thanks for finding.

A PR will happily be accepted to add `--force` support.

**Comment by alangarf** [comment]
@witrin we've just had someone push a PR to support force unmounting. This should fix your issue. I'm pushing out a new release which will have this.
