### ISSUE TITLE
Vagrant halt/up + Mac OSX writes bad /etc/exports

### ISSUE THREAD

**Issue by nmcclay** [Learnosity/vagrant-nfs_guest#36]
If I setup my local VagrantFile like so:

```
config.vm.synced_folder "/Users/nikkio/vagrant", "/home/vagrant/sandbox", type: 'nfs_guest'
```

Everything works fine the first time I seem to setup the VM.  However after running `vagrant halt` -> `vagrant up` I see this error:

```
    default: VirtualBox Version: 5.1
==> default: Configuring and enabling network interfaces...
==> default: Exporting NFS shared folders from guest...
==> default: Setup firewall on the guest to allow NFS exports...
==> default: Preparing to edit /etc/exports on the guest...
Something failed while applying changes to the NFS service on the guest.
exportfs -r
Stdout from the command:
Stderr from the command:
exportfs: /etc/exports:1: syntax error: bad option list
```

Digging into the `/etc/exports` file I see these duplicated mount instructions:

```
# VAGRANT-NFS_GUEST-BEGIN
"/home/vagrant/sandbox" 192.168.33.1(rw,no_subtree_check,all_squash,insecure,anonuid=Agent pid 3803,anongid=Agent pid 3885,fsid=3124099234)
# VAGRANT-NFS_GUEST-END
# VAGRANT-NFS_GUEST-BEGIN
"/home/vagrant/sandbox" 192.168.33.1(rw,no_subtree_check,all_squash,insecure,anonuid=Agent pid 3803,anongid=Agent pid 3885,fsid=3124099234)
# VAGRANT-NFS_GUEST-END
# VAGRANT-NFS_GUEST-BEGIN
"/home/vagrant/sandbox" 192.168.33.1(rw,no_subtree_check,all_squash,insecure,anonuid=Agent pid 3803,anongid=Agent pid 3885,fsid=3124099234)
# VAGRANT-NFS_GUEST-END
# VAGRANT-NFS_GUEST-BEGIN
"/home/vagrant/sandbox" 192.168.33.1(rw,no_subtree_check,all_squash,insecure,anonuid=Agent pid 3803,anongid=Agent pid 3885,fsid=3124099234)
# VAGRANT-NFS_GUEST-END
# VAGRANT-NFS_GUEST-BEGIN
"/home/vagrant/sandbox" 192.168.33.1(rw,no_subtree_check,all_squash,insecure,anonuid=Agent pid 3803,anongid=Agent pid 3885,fsid=3124099234)
# VAGRANT-NFS_GUEST-END
# VAGRANT-NFS_GUEST-BEGIN
"/home/vagrant/sandbox" 192.168.33.1(rw,no_subtree_check,all_squash,insecure,anonuid=Agent pid 3803,anongid=Agent pid 3885,fsid=3124099234)
# VAGRANT-NFS_GUEST-END
# VAGRANT-NFS_GUEST-BEGIN
"/home/vagrant/sandbox" 192.168.33.1(rw,no_subtree_check,all_squash,insecure,anonuid=Agent pid 3803,anongid=Agent pid 3885,fsid=3124099234)
# VAGRANT-NFS_GUEST-END
# VAGRANT-NFS_GUEST-BEGIN
"/home/vagrant/sandbox" 192.168.33.1(rw,no_subtree_check,all_squash,insecure,anonuid=Agent pid 3803,anongid=Agent pid 3885,fsid=3124099234)
# VAGRANT-NFS_GUEST-END
```

Out of curiousity I attempted manually adjusting this file to:

```
# VAGRANT-NFS_GUEST-BEGIN
/home/vagrant/sandbox 192.168.33.1(rw,no_subtree_check,all_squash,insecure,anonuid=3803,anongid=3885,fsid=3124099234)
# VAGRANT-NFS_GUEST-END
```

If I manually run `exportfs -ra`, and then `vagrant suspend` -> `vagrant resume` this successfully remounts the nfs_guest directory as I would have expected from halt/up.  It seems to me that something is going awry in the nfs_guest halt/up hooks on OSX/Virtualbox.

**Comment by nmcclay** [comment]
oh yes, I'm running:
- host - OS X El Capitan - 10.11.6
- guest - centos-release-6-5.el6.centos.11.1.x86_64
- virtualbox - 5.1

**Comment by nmcclay** [comment]
correction, the above only works as a readonly mount :(

**Comment by alangarf** [comment]
Hi, thanks for the post. We've not noticed this behavior with over 60 devs running on El Crapitan with Ubuntu. I'll endeavour to try and replicate and see what I can come up with.

**Comment by nmcclay** [comment]
I did end up coming up with a fix that works.  Basically I had to manually configure my shared folder uid & gid to '500' then this works as expected every time.  I thought to try this after observing that the mount works differently this first time the VM is created (vagrant destroy -> vagrant up).  Looking at /etc/exports I saw these ids were set to '500'.  No clue why this is or why it would be different but it unblocked me from this issue in the short term.

**Comment by alangarf** [comment]
`anonuid=Agent pid 3803,anongid=Agent pid 3885`

Ahh I think I see the issue. Looks like a compatibility issue with centos. I'll figure it out and push a patch release.

Thanks for the report!

**Comment by alangarf** [comment]
One quick one: https://github.com/Learnosity/vagrant-nfs_guest/blob/master/lib/vagrant-nfs_guest/guests/linux/cap/read_user_ids.rb

What does `id -u` and `id -g` return when you run that in centos? Can you please post the output. Thanks!

**Comment by nmcclay** [comment]
Yep, that appears to match the vagrant uid/gid:

```
[vagrant@localhost ~]$ id -u
500
[vagrant@localhost ~]$ id -g
500
```

Thanks for your help!
