### ISSUE TITLE
Missing provider support for VMWare Fusion

### ISSUE THREAD

**Issue by RReverser** [Learnosity/vagrant-nfs_guest#37]
I guess not really a "bug", rather a feature request. Got this while trying to set up an NFS share using this plugin (previously set it up manually fine, just wanted to automate the process):

```
Missing provider support in vagrant-nfs_guest plugin for retrieving host and guest IPs.

Currently only Virtualbox provider is supported.
```

As far as I can tell from https://github.com/Learnosity/vagrant-nfs_guest/tree/master/lib/vagrant-nfs_guest/providers, the "only Virtualbox provider is supported" message is likely outdated at this point.

I'm using VMWare Fusion as it given a better performance on OSX. I'd be happy to help to add a new provider (generally template seems to be relatively simple), but I don't have much experience with Ruby and neither know APIs of VMWare Fusion I would need to use to retrieve needed params for `nfs_settings` :(

**Comment by alangarf** [comment]
Hi there,

The main issue with providing VMWare support is the vagrant plugin for the provider itself is closed source. I could figure out how to get the `nfs_settings` from the API directly, but realistically I don't have VMWare install nor do I use it.

The plugin has support for `lxc, `parallels` and `docker` now, so adding an additional provider is really easy, but not having access to the code of the VMWare provider plugin, or having the software to be able to test it, I'm not really sure I can help right this moment.

Happy to take a PR from someone who has VMWare and the plugin, or happy to help where I can.

Also, yeah that error message is a bit old. I'll fix that.

Cheers! :+1:

**Comment by RReverser** [comment]
@alangarf Ah I see... Does Ruby have ways to reverse-engineer list of available methods etc. by e.g. dumping entire `machine.provider` object?

Alternatively, maybe it's possible to run some universal command on target machine to get host IP as you're doing in `lx`? (if I understand correctly from the source code, guest IP is not a problem and can be retrieved everywhere via `provider.ssh_info[:host]`?)

Finally, if neither is an option, perhaps adding plugin config to set host IP manually would help? (in most cases it doesn't change after the VM network has been set up)

**Comment by alangarf** [comment]
@RReverser yup that is something we can add.

I might reinstall Fusion and the plugin (I paid for it a while ago) and see what I can see. Don't hold your breath however. :)

**Comment by alangarf** [comment]
Unless someone can help with a current VMWare plugin license for Vagrant I can't do much with this issue, so I'm going to close it for now.
