### ISSUE TITLE
Feature: create directory on host if it not exists

### ISSUE THREAD

**Issue by jojoob** [Learnosity/vagrant-nfs_guest#38]
It would be nice if the plugin could create the mount directory on the host if it does not exist (maybe with the possibility to turn this behavior on/off with an argument passed to config.vm.synced_folder).

Current behavior when the directory does not exist on the host machine is aborting with an error message:
```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The host path of the shared folder is missing: nfs_guest
```

## Environment
Host: Mac OS X 10.11.6
Vagrant 1.8.7
vagrant-nfs_guest plugin 0.1.10
Guest: Ubuntu 14.04

**Comment by jojoob** [comment]
Sorry, I've just to RTFM. Of course such an option is provided by vagrant: https://www.vagrantup.com/docs/synced-folders/basic_usage.html#create

Anyway, since vagrant [handles the folder creation](https://github.com/mitchellh/vagrant/blob/159fca9d1338d3d645f4b05cd0d569565a2aa2d9/lib/vagrant/action/builtin/synced_folders.rb#L54) it seems not necessary [to do so in the plugin](https://github.com/Learnosity/vagrant-nfs_guest/blob/98398a07c83da3228efb635ee674a1be9a51f926/lib/vagrant-nfs_guest/hosts/linux/cap/mount_nfs.rb#L21).

**Comment by alangarf** [comment]
Haha, cheers mate. Glad you sorted it. 👍 

-A.
