### ISSUE TITLE
Problems when current working dir is not the Vagrantfile location

### ISSUE THREAD

**Issue by jojoob** [Learnosity/vagrant-nfs_guest#39]
The plugin does not consider the current working directory when doing actions. Therefore, if the host path is specified relative (like in the example) and the current working directory is not the Vagrantfile location some actions behave not as expected or fail.

The host path is used relative to the current working directory by the plugin instead of relative to the Vagrantfile location. Which leads to mounts done at unexpected locations or unmounts fail because a wrong path is used when unmounting (but the vagrant halt is not aborted so the still existing mount can not reach the server).

Another problem would occur even when the correct path is used for umounting but the current working directory is inside the mount point umount will respond "Resource busy". If force unmounting would be used the working dir will left in nowhere (`ls: .: No such file or directory`).

I suggest to use paths relative to the Vagrantfile and `<server>:<mount>` for unmounting instead of mount point and if the current working directory is inside the mount point either abort or change the directory before unmounting. If umount does not exit with status code 0 the vagrant halt should be aborted if possible to avoid "nfs server not responding" warnings at the host. If using `vagrant halt --force` the unmounting could also use the force switch and should not block regardless of the exit code.

I don't know if my suggestions and thoughts are realizable. I'm sorry for just asking for features and not doing a pull request but my ruby knowledge is near zero.

## Environment
The described problems were found with the following setup:

Host: Mac OS X 10.11.6
Vagrant 1.8.7
vagrant-nfs_guest plugin 0.1.10
Guest: Ubuntu 14.04

**Comment by jojoob** [comment]
> [...] if the current working directory is inside the mount point either abort or change the directory before unmounting.

Changing the working directory of the executing ruby script is not enough because the terminal's working directory will be not effected of it. Therefore, the unmount will still fail with "Resource busy".
Changing the terminal's working directory from a child process is not possible as far as I know.
Anyway, the current behaviour which is aborting the action with the "NFS mounts still in use!" message is fair enough.

**Comment by jojoob** [comment]
Did anyone know how a force halt can be differentiated from a normal halt?

**Comment by jojoob** [comment]
> Did anyone know how a force halt can be differentiated from a normal halt?

I've figured it out, the information is stored in the `env[:force_halt]` variable.

```ruby
if env[:force_halt]
  # If this is a force halt, force unmount the nfs shares.
  opts[:unmount_options] = opts.fetch(:unmount_options, []) << '-f'
  # We have to change the working dir if inside a hostmount to prevent "No such file or directory - getcwd" errors.
  if Dir.pwd.start_with?(opts[:hostpath])
    Dir.chdir("#{opts[:hostpath]}/..")
  end
end
```

I'll open a pull request after #40 is merged because this is based on the changes included in this pull request.

**Comment by alangarf** [comment]
Sorry, didn't really get a chance to read this issue. I've merged your other PR, happy to see what you've got with this one. After you push, and I test I'll release a new patch version to rubygems.

Thanks again.
