### ISSUE TITLE
Directory not mounted when after resume machine from suspend state

### ISSUE THREAD

**Issue by rafaelcaceres** [Learnosity/vagrant-nfs_guest#4]
When I suspend my vbox with vagrant and try to resume, the shared folder is not mounted and I have to reload vagrant to work again.

can anyone help me?

**Comment by vangberg** [comment]
@alangarf Any progress on this?

**Comment by alangarf** [comment]
@vangberg no, but I have been meaning to get this cleaned up. To be honest we barely ever suspend boxes so it's not become a recurring issue that I'd notice unless looking. I'll have a look at this soon.

**Comment by coffeemedia** [comment]
Few months later... any luck on this yet?
Switching between different boxes quite a lot lately. Would be great if this could be achieved without `vagrant resume` followed by `vagrant reload`.
Cheers!

**Comment by alangarf** [comment]
@coffeemedia fair enough, to be honest we don't run into that issue that much so never really pops up on the radar. I'll add a ticket to get into it. Thanks.

**Comment by alangarf** [comment]
@coffeemedia @vangberg @rafaelcaceres This should *finally* be fixed with : https://github.com/Learnosity/vagrant-nfs_guest/pull/21

Took a while and boy it was nasty to fix. Only supporting VirtualBox at this time.

**Comment by coffeemedia** [comment]
@alangarf Nice!

**Comment by alangarf** [comment]
All merged and should be fixed in v0.1.7
