### ISSUE TITLE
synced folders disable not properly

### ISSUE THREAD

**Issue by jojoob** [Learnosity/vagrant-nfs_guest#42]
This issue describes two related phenomena from a user perspective.

# 1. The 'disabled' option is not respected
The plugin does not respect the 'disabled' option for synced folders.

Reproduce:
1. Append `, disabled: true` to the synced folders definition at [Vagrantfile:24](https://github.com/Learnosity/vagrant-nfs_guest/blob/3e1c00d7ec2864bcd46d58b46d5880b63abf46c3/example_box/Vagrantfile#L24)
2. Start the vagrant machine `bundle exec vagrant up`
3. list the host mounts via `mount`; inspect the folder 'vagrant_share'

    Expected: No existing mount from the vagrant machine on the host. 'vagrant_machine' folder empty or not existing.

    Actual: The share is still mounted.

# 2. Removing a synced folder definition at runtime does not properly unmount the share from host
If a previously existing synced folder definition is removed from the Vagrantfile while the machine is running the share will not be unmounted from the host (not immediately of course but also not on halt, reload, etc.).

Reproduce:
1. Start up the example_box with unchanged [Vagrantfile](https://github.com/Learnosity/vagrant-nfs_guest/blob/3e1c00d7ec2864bcd46d58b46d5880b63abf46c3/example_box/Vagrantfile): `bundle exec vagrant up`
2. comment out the synced folder definition: [Vagrantfile:24](https://github.com/Learnosity/vagrant-nfs_guest/blob/3e1c00d7ec2864bcd46d58b46d5880b63abf46c3/example_box/Vagrantfile#L24)
3. execute `bundle exec vagrant reload`

    Expected: The share gets unmounted from the host.

    Actual: The share is still mounted (because it was not unmounted from the host and the share definition is still present in the guest).

4. execute `bundle exec vagrant halt`

    Expected: The share gets unmounted from the host.

    Actual: The share is still mounted. Accessing the share results in a timeout.

From a technical perspective this issue might be hard to solve.

**Comment by alangarf** [comment]
Issue #1 is now fixed. Issue #2 I'm less worried about. Modifying the Vagrantfile on a running VM is kinda like changing the sparkplugs of a running car. Explosions may happen. So don't do that. :)

Dealing with the old state, when Vagrant itself has no possible way to know about it if it's been removed would be problematic to solve. You'd need to store the state (or make the plugin understand the existing state in the /etc/exports file) to handle this clean up. I'm going to mark this one down as a "just don't do that". 👍

**Comment by jojoob** [comment]
Thanks @alangarf, I'm happy with the warning "Explosions may happen". ;)
