### ISSUE TITLE
File owner of files inside a synced folder gets overridden during vagrant up

### ISSUE THREAD

**Issue by jojoob** [Learnosity/vagrant-nfs_guest#43]
Reproduce:
1. Start the example_box: `bundle exec vagrant up`
2. ssh to the machine: `bundle exec vagrant ssh`
3. create a new user: `sudo adduser --disabled-login --gecos '' newuser`
4. create a file inside synced folder owned by the new user: `touch /vagrant/test && sudo chown newsuer /vagrant/test`
5. `bundle exec vagrant halt && bundle exec vagrant up`
6. inspect the test file

    Expected: File owner of the test file is 'newuser'

    Actual: File owner of the test file is 'vagrant'

If I append `, disabled: true` to the synced folder definition (the synced folder will actual not be disabled, see #42) the file owner gets not changed. Seems the override happens inside the [enable() method](https://github.com/Learnosity/vagrant-nfs_guest/blob/3e1c00d7ec2864bcd46d58b46d5880b63abf46c3/lib/vagrant-nfs_guest/synced_folder.rb#L24).

**Comment by jojoob** [comment]
This is caused by the [chown command in nfs_opts_setup() method](https://github.com/Learnosity/vagrant-nfs_guest/blob/3e1c00d7ec2864bcd46d58b46d5880b63abf46c3/lib/vagrant-nfs_guest/guests/linux/cap/nfs_server.rb#L153-L157).

When commenting these lines out **it works for me at the moment**. But I assume there is a reason for this command I'm not aware of. Why is this necessary?

**Comment by alangarf** [comment]
As this is an in house plugin we use for our dev environment I think the chown is a legacy thing back from when this plugin was first written. I'll have a look at this and see if it can be stripped out.

Thanks.

**Comment by jojoob** [comment]
Without the [chown command](https://github.com/Learnosity/vagrant-nfs_guest/blob/3e1c00d7ec2864bcd46d58b46d5880b63abf46c3/lib/vagrant-nfs_guest/guests/linux/cap/nfs_server.rb#L153-L157) the mount point inside the vm is owned by root  causing the vagrant user has no write permission.

Maybe a better solution is to just remove the -R option from the chown command.

**Comment by alangarf** [comment]
Sorry I've not got back to this, crazy work/life balance at the moment.

Yup, that makes sense. I'll make the change and see what breaks.

**Comment by alangarf** [comment]
Fix in: https://github.com/Learnosity/vagrant-nfs_guest/commit/4b06c5fad4da5fa14aae7da54e60b5da89478952
