### ISSUE TITLE
New release w/ Ubuntu host support

### ISSUE THREAD

**Issue by ergonlogic** [Learnosity/vagrant-nfs_guest#7]
Hi there,

The fix from #6 appears to allow this plugin to work nicely on my Debian Jessie host. I notice that the pull request was merged in October, but the latest release dates back to July.  It doesn't look like there's been any other substantial changes, but it seems like Linux support (at least for Debian derivatives) is worthy of a minor point release.

**Comment by alangarf** [comment]
Sure. I'll push a release today. Sorry didn't see this issue in my huge list. :) :+1:

**Comment by alangarf** [comment]
Done.
