### ISSUE TITLE
Silent failure when NFS server not installed on guest

### ISSUE THREAD

**Issue by ergonlogic** [Learnosity/vagrant-nfs_guest#8]
When an NFS server isn't installed on the guest, this plugin fails silently. It might be more helpful to emit a warning. Better yet, go ahead and install an NFS server in the guest. For example, the vagrant-bindfs plugin appears to handle this pretty well: https://github.com/gael-ian/vagrant-bindfs/tree/HEAD/lib/vagrant-bindfs/cap

**Comment by alangarf** [comment]
Yup, we should error on the missing nfs_server guest capability.

We only use Ubuntu internally so we've only implemented the nfs_server guest capability for it. If you'd like to implement a guest capability for your OS flavour I'd be happy to merge a pull request.

You can use this as the basis: https://github.com/Learnosity/vagrant-nfs_guest/blob/master/lib/vagrant-nfs_guest/guests/ubuntu/cap/nfs_server.rb
